apiVersion: v1
kind: Service
metadata:
  name: supply-chain-demo
  namespace: supply-chain-demo
  labels:
    app.kubernetes.io/name: supply-chain-demo
    app.kubernetes.io/part-of: supply-chain-security-pipeline
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: supply-chain-demo
